---
title: "Day 2 homework"
author: "Lewis White"
date: "2022-08-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)
```



```{r}
expression_1 <- expression(x ^ 2)

deriv_expression_1 <- D(expression_1, "x")
deriv_expression_1
#2x

## can you add the x value directly into the eval equation???? like "eval(deriv_expression_1, x = 3)"

x <- 3
eval(deriv_expression_1)
#6

expression_2 <- expression(2 * (3* a + 2) ^ 4 - 5)

deriv_expression_2 <- D(expression_2, "a")
deriv_expression_2
#2 * (4 * (3 * (3 * a + 2)^3))

a <- 1.2
eval(deriv_expression_2)
#4214.784

expression_3 <- expression(-4 * t * ((t ^ 2 + 1) ^ 3))

deriv_expression_3 <- D(expression_3, "t")
deriv_expression_3
#-4 * t * (3 * (2 * t * (t^2 + 1)^2)) - 4 * ((t^2 + 1)^3)

t <- 0
eval(deriv_expression_3)
#-4
```



## creating plot of penguins

```{r}
ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm)) +
  geom_point(aes(color = species), size = 1) +
  labs (x = "bill length (mm)", y = "bill depth (mm)", title = "Bill length and depth of penguins") + 
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "steel blue"))
```


